spring.application.name=platform-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_queue_db?createTableIfNotExist=true
spring.datasource.username=parulramrakha
spring.datasource.password=Parul@0312
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
logging.level.com.qms.platform=DEBUG
